package component:cargo-comp

interface imports {

  record listen-details {
    selector: string,
    ty: string,
    value: string
  }

  prnt: func(msg: string)
  addeventlistener: func(details: listen-details)
}

/// An example world for the component to target.
world example {

    import imports

    // creates and returns a new HTML
    export render: func(name: string) -> string
    // adds event listener to the elements
    export listen: func()

}
