package demo:vowels;

interface types {

  // Details required in order to add an event listener to an element
  record listen-details {
    selector: string,
    ty: string,
  }

  // Context for the minijinja rendering
  record page {
    title: string
  }

  record input {
    placeholder: string
  }

  record output {
    value: string,
    // optional id string: None is intial render, Some for update value
    id: option<string>,
    template: option<string>
  }

  // COntent for the entire page
  record content {
    page: page,
    input: input,
    output: option<output>,
  }

  // Context variants
  variant context {
    all-content(content),
    phrase(string)
  }

}

// interface core {
//
//   // Core functionality
//   calculate: func(input: string) -> string;
// }

interface wurbo-in {

  use types.{listen-details};

  // Add an event listener to the given element
  addeventlistener: func(details: listen-details);

}

interface wurbo-out {

  use types.{context};

  // renders the initial Web component with the given data
  render: func(ctx: context) -> result<string, string>;

  // activate listening 
  activate: func(selectors: option<list<string>>);
}

/// An example world for the component to target.
world main {
  import wurbo-in;
  export wurbo-out;
}
