[package]
name = "wurbo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
render = "0.3.1"
lazy_static = "1.4.0"
