package demo:vowels;

interface types {

  // Details required in order to add an event listener to an element
  record listen-details {
    selector: string,
    ty: string,
    value: string
  }

}

interface imports {

  use types.{listen-details};

  // print to the console
  prnt: func(msg: string);

  // Add an event listener to the given element
  addeventlistener: func(details: listen-details);

}

interface reactivity {
  // renders the initial Web component with the given data
  render: func(name: string) -> string;

  // activate listening 
  activate: func();
}

/// An example world for the component to target.
world example {
  import imports;
  export reactivity;
}
