package demo:vowels;

interface types {

  // Details required in order to add an event listener to an element
  record listen-details {
    selector: string,
    ty: string,
    outputid: string
  }

  // Context for the minijinja rendering
  record page {
    title: string
  }

  record input {
    placeholder: string
  }

  record output {
    name: string,
    // optional id string: None is intial render, Some for update value
    id: option<string>
  }

  record context {
    page: page,
    input: input,
    output: output
  }

}

// interface core {
//
//   // Core functionality
//   calculate: func(input: string) -> string;
// }

interface imports {

  use types.{listen-details};

  // print to the console
  prnt: func(msg: string);

  // Add an event listener to the given element
  addeventlistener: func(details: listen-details);

}

interface reactivity {

  use types.{context};

  // renders the initial Web component with the given data
  render: func(ctx: context) -> string;

  // activate listening 
  activate: func();
}

/// An example world for the component to target.
world main {
  import imports;
  export reactivity;
}
